version: '3'

services:
  odoo-fr:
      container_name: web
      build: .
#      command: "python odoo-bin --db_host=172.16.250.78 --db_port=5432 -r opi -w frontiir"
      command: "python odoo-bin -d odoo15test --db_host=192.168.1.8 --db_port=5432 -r opi -w letmein"
